FROM python:3.12-slim
RUN pip install uv
WORKDIR /app
COPY . .
RUN uv sync
EXPOSE 8080
CMD sh -c 'echo "GOOGLE_ADS_DEVELOPER_TOKEN=${GOOGLE_ADS_DEVELOPER_TOKEN}\nGOOGLE_ADS_CLIENT_ID=${GOOGLE_ADS_CLIENT_ID}\nGOOGLE_ADS_CLIENT_SECRET=${GOOGLE_ADS_CLIENT_SECRET}\nGOOGLE_ADS_REFRESH_TOKEN=${GOOGLE_ADS_REFRESH_TOKEN}\nGOOGLE_ADS_LOGIN_CUSTOMER_ID=${GOOGLE_ADS_LOGIN_CUSTOMER_ID}" > .env && uv run main.py'
